# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798964157410d3c3facc11056cbb9ae8c3a016129dff96c07619df1ba12be6d034ea986cc140399bdedd1479ca1e190740892ff4d0045c6666fcfcd345116241

test:
  secret_key_base: 63a1603b319e3d577b94094ec02890b730f144c102dde500559d746277d1f663be7e0b2862ae4ce52b0ac9015f77878e5432e4a7771c3ccde5f5a27f75bfe6b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
